<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MomEase.app\MomEase.app.csproj" />
    <ProjectReference Include="..\MomEase.core\MomEase.core.csproj" />
    <ProjectReference Include="..\MomEase.infra\MomEase.infra.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\uploads\children\" />
  </ItemGroup>

</Project>
