// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MomEase.infra.Data;

#nullable disable

namespace MomEase.infra.Migrations
{
    [DbContext(typeof(MomEaseDbContext))]
    [Migration("20260303234126_EmptyMigration")]
    partial class EmptyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MomEase.core.Entities.AnswerOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<int?>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("MomEase.core.Entities.ArticleCategories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("MomEase.core.Entities.Articles", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("MomEase.core.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("MomEase.core.Entities.AssessmentResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentResults");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChatBot", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatBots");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChatMessages", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MomEase.core.Entities.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<int>("FeedingTypeForBaby")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChildId");

                    b.HasIndex("UserId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildFeedingRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FeedingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeedingRefId")
                        .HasColumnType("int");

                    b.Property<int>("FeedingTimesPerDay")
                        .HasColumnType("int");

                    b.Property<int>("FeedingType")
                        .HasColumnType("int");

                    b.Property<int>("FeedingTypeForBaby")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecordId");

                    b.HasIndex("ChildId");

                    b.HasIndex("FeedingRefId");

                    b.ToTable("ChildFeedingRecords");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildSleepRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SleepDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("SleepHoursTotal")
                        .HasColumnType("time");

                    b.Property<int?>("SleepRefId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("ChildId");

                    b.HasIndex("SleepRefId");

                    b.ToTable("ChildSleepRecords");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildVaccination", b =>
                {
                    b.Property<int>("ChildVaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildVaccineId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TakenDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ChildVaccineId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ChildVaccinations");
                });

            modelBuilder.Entity("MomEase.core.Entities.CommunityPosts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityPosts");
                });

            modelBuilder.Entity("MomEase.core.Entities.CryAnalyses", b =>
                {
                    b.Property<int>("CryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CryId"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int?>("CryreasonId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CryId");

                    b.HasIndex("ChildId");

                    b.HasIndex("CryreasonId");

                    b.HasIndex("UserId");

                    b.ToTable("CryAnalyses");
                });

            modelBuilder.Entity("MomEase.core.Entities.CryReasons", b =>
                {
                    b.Property<int>("CryreasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CryreasonId"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CryreasonId");

                    b.ToTable("CryReasons");
                });

            modelBuilder.Entity("MomEase.core.Entities.Diseases", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("MomEase.core.Entities.FeedingReference", b =>
                {
                    b.Property<int>("FeedingRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedingRefId"));

                    b.Property<int?>("AgeMaxMonths")
                        .HasColumnType("int");

                    b.Property<int?>("AgeMinMonths")
                        .HasColumnType("int");

                    b.Property<int>("FeedingTypeForBaby")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTimesPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("MinTimesPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FeedingRefId");

                    b.ToTable("FeedingReferences");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthPercentileReference", b =>
                {
                    b.Property<int>("RefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefId"));

                    b.Property<int>("AgeMonths")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Metric_Type")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("P10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P25")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P75")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P90")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P95")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RefId");

                    b.HasIndex("Gender", "AgeMonths", "Metric_Type")
                        .IsUnique();

                    b.ToTable("GrowthPercentileReferences");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthRecords", b =>
                {
                    b.Property<int>("GrowthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrowthId"));

                    b.Property<int>("AgeInWeeks")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GrowthId");

                    b.HasIndex("ChildId");

                    b.ToTable("GrowthRecords");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int?>("GrowthStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("ChildId");

                    b.HasIndex("RefId");

                    b.ToTable("GrowthReports");
                });

            modelBuilder.Entity("MomEase.core.Entities.MotherProfile", b =>
                {
                    b.Property<int>("MotherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotherId"));

                    b.Property<int?>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstTimeMother")
                        .HasColumnType("bit");

                    b.Property<int?>("MentalHealthStatus")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MotherId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MotherProfiles");
                });

            modelBuilder.Entity("MomEase.core.Entities.Notifications", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MomEase.core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostComments", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostMedia", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("MediaId");

                    b.HasIndex("PostId");

                    b.ToTable("PostMedias");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostReactions", b =>
                {
                    b.Property<int>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionId"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostReports", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("PostId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("PostReports");
                });

            modelBuilder.Entity("MomEase.core.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReverse")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("MomEase.core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MomEase.core.Entities.SavedArticles", b =>
                {
                    b.Property<int>("SavedArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedArticleId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedArticleId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId", "ArticleId")
                        .IsUnique();

                    b.ToTable("SavedArticles");
                });

            modelBuilder.Entity("MomEase.core.Entities.ScoreLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("MinScore")
                        .HasColumnType("int");

                    b.HasKey("LevelId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("ScoreLevels");
                });

            modelBuilder.Entity("MomEase.core.Entities.SearchHistory", b =>
                {
                    b.Property<int>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchId"));

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SearchId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("MomEase.core.Entities.SkinAnalyses", b =>
                {
                    b.Property<int>("SkinanalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkinanalysisId"));

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SkinanalysisId");

                    b.HasIndex("ChildId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("UserId");

                    b.ToTable("SkinAnalyses");
                });

            modelBuilder.Entity("MomEase.core.Entities.SleepReference", b =>
                {
                    b.Property<int>("SleepRefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SleepRefId"));

                    b.Property<int?>("AgeMaxMonths")
                        .HasColumnType("int");

                    b.Property<int?>("AgeMinMonths")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("SleepMaxHours")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("SleepMinHours")
                        .HasColumnType("time");

                    b.HasKey("SleepRefId");

                    b.ToTable("SleepReferences");
                });

            modelBuilder.Entity("MomEase.core.Entities.UserResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<int>("ComputedScore")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserResponses");
                });

            modelBuilder.Entity("MomEase.core.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternalAuth")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MomEase.core.Entities.Vaccinations", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("DiseasePrevented")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DoseTiming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaccinationWay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vaccine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ScheduleId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("MomEase.core.Entities.AnswerOption", b =>
                {
                    b.HasOne("MomEase.core.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MomEase.core.Entities.ArticleCategories", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", null)
                        .WithMany("ArticleCategories")
                        .HasForeignKey("UsersUserId");
                });

            modelBuilder.Entity("MomEase.core.Entities.Articles", b =>
                {
                    b.HasOne("MomEase.core.Entities.ArticleCategories", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MomEase.core.Entities.AssessmentResult", b =>
                {
                    b.HasOne("MomEase.core.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.ScoreLevel", "ScoreLevel")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("AssessmentResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("ScoreLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChatBot", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("ChatBots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChatMessages", b =>
                {
                    b.HasOne("MomEase.core.Entities.ChatBot", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("MomEase.core.Entities.Child", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("Children")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildFeedingRecord", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("ChildFeedingRecords")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.FeedingReference", "FeedingReference")
                        .WithMany("ChildFeedingRecords")
                        .HasForeignKey("FeedingRefId");

                    b.Navigation("Child");

                    b.Navigation("FeedingReference");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildSleepRecord", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("ChildSleepRecords")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.SleepReference", "SleepReference")
                        .WithMany("ChildSleepRecords")
                        .HasForeignKey("SleepRefId");

                    b.Navigation("Child");

                    b.Navigation("SleepReference");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChildVaccination", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("ChildVaccinations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Vaccinations", "Vaccination")
                        .WithMany("ChildVaccinations")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Vaccination");
                });

            modelBuilder.Entity("MomEase.core.Entities.CommunityPosts", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.CryAnalyses", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("CryAnalyses")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.CryReasons", "CryReason")
                        .WithMany("CryAnalyses")
                        .HasForeignKey("CryreasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("CryAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("CryReason");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthRecords", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("GrowthRecords")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthReports", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("GrowthReports")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.GrowthPercentileReference", "GrowthPercentileReference")
                        .WithMany("GrowthReports")
                        .HasForeignKey("RefId");

                    b.Navigation("Child");

                    b.Navigation("GrowthPercentileReference");
                });

            modelBuilder.Entity("MomEase.core.Entities.MotherProfile", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithOne("MotherProfile")
                        .HasForeignKey("MomEase.core.Entities.MotherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.Notifications", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostComments", b =>
                {
                    b.HasOne("MomEase.core.Entities.CommunityPosts", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostMedia", b =>
                {
                    b.HasOne("MomEase.core.Entities.CommunityPosts", "Post")
                        .WithMany("PostMedia")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostReactions", b =>
                {
                    b.HasOne("MomEase.core.Entities.CommunityPosts", "Post")
                        .WithMany("PostReactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.PostReports", b =>
                {
                    b.HasOne("MomEase.core.Entities.CommunityPosts", "Post")
                        .WithMany("PostReports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", "Reporter")
                        .WithMany("SubmittedReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", "ReviewedBy")
                        .WithMany("ReviewedReports")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Post");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("MomEase.core.Entities.Question", b =>
                {
                    b.HasOne("MomEase.core.Entities.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("MomEase.core.Entities.RefreshToken", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.SavedArticles", b =>
                {
                    b.HasOne("MomEase.core.Entities.Articles", "Article")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("SavedArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.ScoreLevel", b =>
                {
                    b.HasOne("MomEase.core.Entities.Assessment", "Assessment")
                        .WithMany("ScoreLevels")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("MomEase.core.Entities.SearchHistory", b =>
                {
                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.SkinAnalyses", b =>
                {
                    b.HasOne("MomEase.core.Entities.Child", "Child")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MomEase.core.Entities.Diseases", "Disease")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MomEase.core.Entities.Users", "User")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Disease");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MomEase.core.Entities.UserResponse", b =>
                {
                    b.HasOne("MomEase.core.Entities.AnswerOption", "AnswerOption")
                        .WithMany("UserResponses")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Question", "Question")
                        .WithMany("UserResponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.AssessmentResult", "AssessmentResult")
                        .WithMany("UserResponses")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MomEase.core.Entities.Users", null)
                        .WithMany("UserResponses")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("AnswerOption");

                    b.Navigation("AssessmentResult");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MomEase.core.Entities.AnswerOption", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MomEase.core.Entities.ArticleCategories", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("MomEase.core.Entities.Articles", b =>
                {
                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("MomEase.core.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentResults");

                    b.Navigation("Questions");

                    b.Navigation("ScoreLevels");
                });

            modelBuilder.Entity("MomEase.core.Entities.AssessmentResult", b =>
                {
                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MomEase.core.Entities.ChatBot", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("MomEase.core.Entities.Child", b =>
                {
                    b.Navigation("ChildFeedingRecords");

                    b.Navigation("ChildSleepRecords");

                    b.Navigation("ChildVaccinations");

                    b.Navigation("CryAnalyses");

                    b.Navigation("GrowthRecords");

                    b.Navigation("GrowthReports");

                    b.Navigation("SkinAnalyses");
                });

            modelBuilder.Entity("MomEase.core.Entities.CommunityPosts", b =>
                {
                    b.Navigation("PostComments");

                    b.Navigation("PostMedia");

                    b.Navigation("PostReactions");

                    b.Navigation("PostReports");
                });

            modelBuilder.Entity("MomEase.core.Entities.CryReasons", b =>
                {
                    b.Navigation("CryAnalyses");
                });

            modelBuilder.Entity("MomEase.core.Entities.Diseases", b =>
                {
                    b.Navigation("SkinAnalyses");
                });

            modelBuilder.Entity("MomEase.core.Entities.FeedingReference", b =>
                {
                    b.Navigation("ChildFeedingRecords");
                });

            modelBuilder.Entity("MomEase.core.Entities.GrowthPercentileReference", b =>
                {
                    b.Navigation("GrowthReports");
                });

            modelBuilder.Entity("MomEase.core.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MomEase.core.Entities.ScoreLevel", b =>
                {
                    b.Navigation("AssessmentResults");
                });

            modelBuilder.Entity("MomEase.core.Entities.SleepReference", b =>
                {
                    b.Navigation("ChildSleepRecords");
                });

            modelBuilder.Entity("MomEase.core.Entities.Users", b =>
                {
                    b.Navigation("ArticleCategories");

                    b.Navigation("AssessmentResults");

                    b.Navigation("ChatBots");

                    b.Navigation("Children");

                    b.Navigation("CommunityPosts");

                    b.Navigation("CryAnalyses");

                    b.Navigation("MotherProfile")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("PostComments");

                    b.Navigation("PostReactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedReports");

                    b.Navigation("SavedArticles");

                    b.Navigation("SearchHistories");

                    b.Navigation("SkinAnalyses");

                    b.Navigation("SubmittedReports");

                    b.Navigation("UserResponses");
                });

            modelBuilder.Entity("MomEase.core.Entities.Vaccinations", b =>
                {
                    b.Navigation("ChildVaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
